#!/usr/bin/env node
// Writes the Swift and CSS token files from tokens.json.
//
//   node DesignSystem/generate.mjs           # write
//   node DesignSystem/generate.mjs --check   # fail if the committed files have drifted
//
// Two platforms reading one file is the whole point: a colour changed in Swift
// but not in CSS is the failure mode this exists to prevent.
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const tokens = JSON.parse(await readFile(join(root, 'DesignSystem/tokens.json'), 'utf8'));

const BANNER = 'Generated by DesignSystem/generate.mjs from DesignSystem/tokens.json.\nEdit the JSON, not this file.';
const isToken = ([key]) => !key.startsWith('_');
const entries = (group) => Object.entries(group).filter(isToken);

// ── colour parsing ───────────────────────────────────────────────────────────

/** "#C8FF00" or "rgba(r, g, b, a)" → { r, g, b, a } in 0…1. */
function parseColor(value) {
  const hex = value.match(/^#([0-9a-f]{6})$/i);
  if (hex) {
    const n = parseInt(hex[1], 16);
    return { r: ((n >> 16) & 255) / 255, g: ((n >> 8) & 255) / 255, b: (n & 255) / 255, a: 1 };
  }
  const rgba = value.match(/^rgba?\(([^)]+)\)$/);
  if (rgba) {
    const [r, g, b, a = '1'] = rgba[1].split(',').map((s) => s.trim());
    return { r: +r / 255, g: +g / 255, b: +b / 255, a: +a };
  }
  throw new Error(`Cannot parse colour: ${value}`);
}

const f = (n) => n.toFixed(4).replace(/0+$/, '').replace(/\.$/, '.0');

// ── Swift ────────────────────────────────────────────────────────────────────

function swiftColor(name, token) {
  const light = parseColor(token.light);
  const dark = parseColor(token.dark);
  const doc = token.use ? `    /// ${token.use}\n` : '';
  // A dynamic NSColor resolves per appearance, so a single token works in both
  // without the call site ever branching on the theme.
  return `${doc}    public static let ${name} = NSColor(name: "${name}") { appearance in
        appearance.isDark
            ? NSColor(srgbRed: ${f(dark.r)}, green: ${f(dark.g)}, blue: ${f(dark.b)}, alpha: ${f(dark.a)})
            : NSColor(srgbRed: ${f(light.r)}, green: ${f(light.g)}, blue: ${f(light.b)}, alpha: ${f(light.a)})
    }`;
}

function swiftFile() {
  const colors = entries(tokens.color).map(([n, t]) => swiftColor(n, t)).join('\n\n');
  const swiftUI = entries(tokens.color)
    .map(([n]) => `    public static var ${n}: Color { Color(nsColor: Ink.${n}) }`).join('\n');
  const space = entries(tokens.space)
    .map(([n, v]) => `    public static let ${n}: CGFloat = ${v}`).join('\n');
  const radius = entries(tokens.radius)
    .map(([n, v]) => `    public static let ${n}: CGFloat = ${v}`).join('\n');
  const motion = entries(tokens.motion)
    .map(([n, v]) => `    public static let ${n}: Double = ${v}`).join('\n');
  const measure = entries(tokens.measure)
    .map(([n, v]) => `    public static let ${n}: CGFloat = ${v}`).join('\n');

  return `// ${BANNER.split('\n').join('\n// ')}

#if canImport(AppKit)
import AppKit
import SwiftUI

extension NSAppearance {
    var isDark: Bool { bestMatch(from: [.aqua, .darkAqua]) == .darkAqua }
}

/// Colour as AppKit sees it. Every token is appearance-aware, so nothing at a
/// call site needs to know which theme is active.
public enum Ink {
${colors}
}

/// The same tokens for SwiftUI.
public enum Palette {
${swiftUI}
}

/// A 4pt grid. Reach for a token, not a number.
public enum Space {
${space}
}

public enum Radius {
${radius}
}

/// Durations in seconds. Respect \`accessibilityReduceMotion\` at the call site.
public enum Motion {
${motion}
}

public enum Measure {
${measure}
}
#endif
`;
}

// ── CSS ──────────────────────────────────────────────────────────────────────

// Pad on the emitted name, not the source key — kebab-case is longer.
function cssVars(group, appearance, indent) {
  const pad = Math.max(...entries(group).map(([n]) => kebab(n).length));
  return entries(group)
    .map(([n, t]) => `${indent}--${kebab(n)}:${' '.repeat(pad - kebab(n).length + 1)}${t[appearance]};`)
    .join('\n');
}

const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();

function cssFile() {
  // The name carries the unit: a token ending in Ch is a character count, Pt a
  // length, and everything in `motion` is seconds.
  const unitFor = (prefix, name) =>
    prefix === 'motion' ? 's' : /Ch$/.test(name) ? 'ch' : 'px';
  const scalars = (prefix, group) =>
    entries(group)
      .map(([n, v]) => `  --${prefix}-${kebab(n)}: ${v}${unitFor(prefix, n)};`)
      .join('\n');

  const light = [cssVars(tokens.color, 'light', '  '), '', cssVars(tokens.webOnly, 'light', '  ')].join('\n');
  const darkInner = [cssVars(tokens.color, 'dark', '    '), '', cssVars(tokens.webOnly, 'dark', '    ')].join('\n');
  const darkRoot = [cssVars(tokens.color, 'dark', '  '), '', cssVars(tokens.webOnly, 'dark', '  ')].join('\n');

  return `/* ${BANNER.split('\n').join('\n   ')} */

/* Light is the base. Dark redefines only the values — once for the unstamped
   system default, once for an explicit toggle — so no rule elsewhere in the site
   needs to know which theme is active. */
:root {
${light}

${scalars('space', tokens.space)}

${scalars('radius', tokens.radius)}

${scalars('motion', tokens.motion)}

${scalars('measure', tokens.measure)}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${darkInner}
  }
}

:root[data-theme="dark"] {
${darkRoot}
}
`;
}

// ── write / check ────────────────────────────────────────────────────────────

const outputs = [
  ['Sources/MilkyUI/DesignSystem/Tokens.generated.swift', swiftFile()],
  ['Web/src/styles/tokens.generated.css', cssFile()],
];

const check = process.argv.includes('--check');
let drifted = false;

for (const [path, contents] of outputs) {
  const full = join(root, path);
  if (check) {
    const existing = await readFile(full, 'utf8').catch(() => null);
    if (existing !== contents) {
      console.error(`drift: ${path} does not match tokens.json`);
      drifted = true;
    }
  } else {
    await writeFile(full, contents);
    console.log(`${path} — ${contents.split('\n').length} lines`);
  }
}

if (check) {
  if (drifted) {
    console.error('\nRun `node DesignSystem/generate.mjs` and commit the result.');
    process.exit(1);
  }
  console.log('tokens are in sync');
}
