// Generated by DesignSystem/generate.mjs from DesignSystem/tokens.json.
// Edit the JSON, not this file.

#if canImport(AppKit)
import AppKit
import SwiftUI

extension NSAppearance {
    var isDark: Bool { bestMatch(from: [.aqua, .darkAqua]) == .darkAqua }
}

/// Colour as AppKit sees it. Every token is appearance-aware, so nothing at a
/// call site needs to know which theme is active.
public enum Ink {
    /// Page and window ground
    public static let surface = NSColor(name: "surface") { appearance in
        appearance.isDark
            ? NSColor(srgbRed: 0.051, green: 0.051, blue: 0.0588, alpha: 1.0)
            : NSColor(srgbRed: 0.9882, green: 0.9882, blue: 0.9843, alpha: 1.0)
    }

    /// A recessed band the content sits on
    public static let surfaceSunken = NSColor(name: "surfaceSunken") { appearance in
        appearance.isDark
            ? NSColor(srgbRed: 0.0784, green: 0.0784, blue: 0.0902, alpha: 1.0)
            : NSColor(srgbRed: 0.9137, green: 0.9137, blue: 0.9059, alpha: 1.0)
    }

    /// Body text
    public static let ink = NSColor(name: "ink") { appearance in
        appearance.isDark
            ? NSColor(srgbRed: 0.9255, green: 0.9255, blue: 0.9373, alpha: 1.0)
            : NSColor(srgbRed: 0.0902, green: 0.0902, blue: 0.1059, alpha: 1.0)
    }

    /// Secondary text; passes AA at 13px
    public static let inkSoft = NSColor(name: "inkSoft") { appearance in
        appearance.isDark
            ? NSColor(srgbRed: 0.5765, green: 0.5765, blue: 0.6157, alpha: 1.0)
            : NSColor(srgbRed: 0.4235, green: 0.4235, blue: 0.4588, alpha: 1.0)
    }

    /// Chrome and non-text marks only
    public static let inkFaint = NSColor(name: "inkFaint") { appearance in
        appearance.isDark
            ? NSColor(srgbRed: 0.4314, green: 0.4314, blue: 0.4745, alpha: 1.0)
            : NSColor(srgbRed: 0.6039, green: 0.6039, blue: 0.6431, alpha: 1.0)
    }

    /// Dividers
    public static let rule = NSColor(name: "rule") { appearance in
        appearance.isDark
            ? NSColor(srgbRed: 1.0, green: 1.0, blue: 1.0, alpha: 0.13)
            : NSColor(srgbRed: 0.0784, green: 0.0784, blue: 0.102, alpha: 0.11)
    }

    /// Hairlines, quiet fills
    public static let ruleSoft = NSColor(name: "ruleSoft") { appearance in
        appearance.isDark
            ? NSColor(srgbRed: 1.0, green: 1.0, blue: 1.0, alpha: 0.07)
            : NSColor(srgbRed: 0.0784, green: 0.0784, blue: 0.102, alpha: 0.06)
    }

    /// FILL ONLY — 1.2:1 on white
    public static let accent = NSColor(name: "accent") { appearance in
        appearance.isDark
            ? NSColor(srgbRed: 0.7843, green: 1.0, blue: 0.0, alpha: 1.0)
            : NSColor(srgbRed: 0.7843, green: 1.0, blue: 0.0, alpha: 1.0)
    }

    /// The accent as a thin mark: text, carets, icons
    public static let accentInk = NSColor(name: "accentInk") { appearance in
        appearance.isDark
            ? NSColor(srgbRed: 0.7843, green: 1.0, blue: 0.0, alpha: 1.0)
            : NSColor(srgbRed: 0.3529, green: 0.451, blue: 0.0, alpha: 1.0)
    }

    /// Text on an accent fill. Does not follow appearance
    public static let onAccent = NSColor(name: "onAccent") { appearance in
        appearance.isDark
            ? NSColor(srgbRed: 0.0549, green: 0.0745, blue: 0.0, alpha: 1.0)
            : NSColor(srgbRed: 0.0549, green: 0.0745, blue: 0.0, alpha: 1.0)
    }

    /// Outbound URLs. Internal links use accentInk
    public static let link = NSColor(name: "link") { appearance in
        appearance.isDark
            ? NSColor(srgbRed: 0.4196, green: 0.6784, blue: 0.9804, alpha: 1.0)
            : NSColor(srgbRed: 0.102, green: 0.4353, blue: 0.8588, alpha: 1.0)
    }

    /// Markdown punctuation, at rest
    public static let syntax = NSColor(name: "syntax") { appearance in
        appearance.isDark
            ? NSColor(srgbRed: 1.0, green: 1.0, blue: 1.0, alpha: 0.26)
            : NSColor(srgbRed: 0.0, green: 0.0, blue: 0.0, alpha: 0.22)
    }

    /// Markdown punctuation on the caret's line
    public static let syntaxActive = NSColor(name: "syntaxActive") { appearance in
        appearance.isDark
            ? NSColor(srgbRed: 1.0, green: 1.0, blue: 1.0, alpha: 0.45)
            : NSColor(srgbRed: 0.0, green: 0.0, blue: 0.0, alpha: 0.38)
    }

    /// Inline code text
    public static let codeInk = NSColor(name: "codeInk") { appearance in
        appearance.isDark
            ? NSColor(srgbRed: 0.9412, green: 0.6196, blue: 0.5647, alpha: 1.0)
            : NSColor(srgbRed: 0.7216, green: 0.2078, blue: 0.298, alpha: 1.0)
    }

    /// Inline code and fenced block ground
    public static let codeSurface = NSColor(name: "codeSurface") { appearance in
        appearance.isDark
            ? NSColor(srgbRed: 1.0, green: 1.0, blue: 1.0, alpha: 0.08)
            : NSColor(srgbRed: 0.0784, green: 0.0784, blue: 0.102, alpha: 0.05)
    }

    /// Tag pill text
    public static let tagInk = NSColor(name: "tagInk") { appearance in
        appearance.isDark
            ? NSColor(srgbRed: 0.8314, green: 0.949, blue: 0.4784, alpha: 1.0)
            : NSColor(srgbRed: 0.2784, green: 0.349, blue: 0.0, alpha: 1.0)
    }

    /// Syntax: declarations and control flow — the brand hue
    public static let codeKeyword = NSColor(name: "codeKeyword") { appearance in
        appearance.isDark
            ? NSColor(srgbRed: 0.7843, green: 1.0, blue: 0.0, alpha: 1.0)
            : NSColor(srgbRed: 0.2902, green: 0.3882, blue: 0.0, alpha: 1.0)
    }

    /// Syntax: strings and characters
    public static let codeString = NSColor(name: "codeString") { appearance in
        appearance.isDark
            ? NSColor(srgbRed: 0.9098, green: 0.7216, blue: 0.4784, alpha: 1.0)
            : NSColor(srgbRed: 0.5412, green: 0.3255, blue: 0.0, alpha: 1.0)
    }

    /// Syntax: numbers, booleans, nil
    public static let codeNumber = NSColor(name: "codeNumber") { appearance in
        appearance.isDark
            ? NSColor(srgbRed: 0.7686, green: 0.651, blue: 1.0, alpha: 1.0)
            : NSColor(srgbRed: 0.4157, green: 0.2039, blue: 0.7804, alpha: 1.0)
    }

    /// Syntax: type names
    public static let codeType = NSColor(name: "codeType") { appearance in
        appearance.isDark
            ? NSColor(srgbRed: 0.4353, green: 0.8471, blue: 0.7843, alpha: 1.0)
            : NSColor(srgbRed: 0.0431, green: 0.4196, blue: 0.3882, alpha: 1.0)
    }

    /// Syntax: comments, set italic
    public static let codeComment = NSColor(name: "codeComment") { appearance in
        appearance.isDark
            ? NSColor(srgbRed: 0.5804, green: 0.5804, blue: 0.6196, alpha: 1.0)
            : NSColor(srgbRed: 0.4275, green: 0.4275, blue: 0.4706, alpha: 1.0)
    }

    /// Syntax: operators and brackets
    public static let codePunctuation = NSColor(name: "codePunctuation") { appearance in
        appearance.isDark
            ? NSColor(srgbRed: 0.5804, green: 0.5804, blue: 0.6196, alpha: 1.0)
            : NSColor(srgbRed: 0.4235, green: 0.4235, blue: 0.4588, alpha: 1.0)
    }

    /// Tag pill ground
    public static let tagSurface = NSColor(name: "tagSurface") { appearance in
        appearance.isDark
            ? NSColor(srgbRed: 0.7843, green: 1.0, blue: 0.0, alpha: 0.2)
            : NSColor(srgbRed: 0.7843, green: 1.0, blue: 0.0, alpha: 0.42)
    }
}

/// The same tokens for SwiftUI.
public enum Palette {
    public static var surface: Color { Color(nsColor: Ink.surface) }
    public static var surfaceSunken: Color { Color(nsColor: Ink.surfaceSunken) }
    public static var ink: Color { Color(nsColor: Ink.ink) }
    public static var inkSoft: Color { Color(nsColor: Ink.inkSoft) }
    public static var inkFaint: Color { Color(nsColor: Ink.inkFaint) }
    public static var rule: Color { Color(nsColor: Ink.rule) }
    public static var ruleSoft: Color { Color(nsColor: Ink.ruleSoft) }
    public static var accent: Color { Color(nsColor: Ink.accent) }
    public static var accentInk: Color { Color(nsColor: Ink.accentInk) }
    public static var onAccent: Color { Color(nsColor: Ink.onAccent) }
    public static var link: Color { Color(nsColor: Ink.link) }
    public static var syntax: Color { Color(nsColor: Ink.syntax) }
    public static var syntaxActive: Color { Color(nsColor: Ink.syntaxActive) }
    public static var codeInk: Color { Color(nsColor: Ink.codeInk) }
    public static var codeSurface: Color { Color(nsColor: Ink.codeSurface) }
    public static var tagInk: Color { Color(nsColor: Ink.tagInk) }
    public static var codeKeyword: Color { Color(nsColor: Ink.codeKeyword) }
    public static var codeString: Color { Color(nsColor: Ink.codeString) }
    public static var codeNumber: Color { Color(nsColor: Ink.codeNumber) }
    public static var codeType: Color { Color(nsColor: Ink.codeType) }
    public static var codeComment: Color { Color(nsColor: Ink.codeComment) }
    public static var codePunctuation: Color { Color(nsColor: Ink.codePunctuation) }
    public static var tagSurface: Color { Color(nsColor: Ink.tagSurface) }
}

/// A 4pt grid. Reach for a token, not a number.
public enum Space {
    public static let xxs: CGFloat = 2
    public static let xs: CGFloat = 4
    public static let sm: CGFloat = 6
    public static let md: CGFloat = 8
    public static let lg: CGFloat = 12
    public static let xl: CGFloat = 16
    public static let xxl: CGFloat = 20
    public static let xxxl: CGFloat = 24
    public static let section: CGFloat = 32
    public static let page: CGFloat = 48
}

public enum Radius {
    public static let sm: CGFloat = 4
    public static let md: CGFloat = 7
    public static let lg: CGFloat = 10
    public static let xl: CGFloat = 14
    public static let capsule: CGFloat = 980
}

/// Durations in seconds. Respect `accessibilityReduceMotion` at the call site.
public enum Motion {
    public static let instant: Double = 0.12
    public static let quick: Double = 0.16
    public static let settle: Double = 0.24
}

public enum Measure {
    public static let readingColumnPt: CGFloat = 720
    public static let proseMaxCh: CGFloat = 68
}
#endif
